```python
try:
    # 可能出现异常的代码
except [a kind of Exception]:
    # 错误恢复代码
finally:
    # 不论错误是否发生,这段代码都会执行
```

异常名称 | 描述
: - :| -
Exception | 所有异常的基类
StopIteration | 当一个迭代器的 next()方法不指向任何对象时引发
SystemExit | 由 sys.exit()函数引发
StandardError | 除了StopIteration异常和SystemExit,所有内置异常的基类
ArithmeticError | 数值计算所发生的所有错误的基类
OverflowError | 当数字类型计算超过最高限额引发
FloatingPointError | 当一个浮点运算失败时触发
ZeroDivisionError | 当除运算或模零在所有数值类型运算时引发
AssertionError | 断言语句失败的情况下引发
AttributeError | 属性引用或赋值失败的情况下引发
EOFError | 当从 raw_input() 与 input() 函数输入,到达文件末尾时触发
ImportError | 当一个 import 语句失败时触发
KeyboardInterrupt | 当用户中断程序执行,通常是通过按 Ctrl+c 引发
LookupError | 所有查找错误基类
IndexError | 当在一个序列中没有找到一个索引时引发
KeyError | 当指定的键没有在字典中找到引发
NameError | 当在局部或全局命名空间中找不到的标识引发
UnboundLocalError | 试图访问在函数或方法的局部变量时引发,但没有值分配给它
EnvironmentError | Python环境之外发生的所有异常的基类
IOError | 当一个输入/输出操作失败,如打印语句或 open()函数试图打开不存在的文件时引发
SyntaxError | 当在Python语法错误引发
IndentationError | 没有正确指定缩进引发
SystemError | 当解释器发现一个内部问题,但遇到此错误时,Python解释器不退出引发
SystemExit | 当Python解释器不使用sys.exit()函数引发。如果代码没有被处理,解释器会退出
ValueError | 在内置函数对于数据类型,参数的有效类型时引发,但是参数指定了无效值
RuntimeError | 当生成的错误不属于任何类别时引发
NotImplementedError | 当要在继承的类来实现,抽象方法实际上没有实现时引发此异常